from api_client import APIClient


class InterviewManager:
    def __init__(self):
        self.sessions = {}
        self.api = APIClient()

    def start_interview(self, user_id: int, direction: str, level: str):
        self.sessions[user_id] = {
            "direction": direction,
            "level": level,
            "theory_answers": [],
            "coding_answers": [],
            "soft_answers": [],
            "current_question": None
        }

    async def get_next_question(self, user_id: int, q_type: str) -> str:
        session = self.sessions.get(user_id)
        if not session: return "Сессия не найдена"

        question = await self.api.generate_question(
            session["direction"],
            session["level"],
            q_type
        )
        session["current_question"] = question
        return question

    async def process_answer(self, user_id: int, answer: str, context_type: str):
        session = self.sessions.get(user_id)
        if not session: return 0, "Ошибка сессии"

        result = await self.api.evaluate_answer(
            context_type,
            session["current_question"],
            answer,
            session["direction"],
            session["level"]
        )

        storage_map = {
            "theory": "theory_answers",
            "coding": "coding_answers",
            "soft_skills": "soft_answers"
        }
        session[storage_map[context_type]].append(result)

        return result.get("score", 0), result.get("feedback", ""), result.get("correct_answer", "")

    def get_final_report(self, user_id: int) -> str:
        session = self.sessions.get(user_id)
        if not session: return "Ошибка: сессия не найдена."

        def avg(lst): return sum(a['score'] for a in lst) / len(lst) if lst else 0

        t_score = avg(session["theory_answers"])
        c_score = avg(session["coding_answers"])
        s_score = avg(session["soft_answers"])
        total = (t_score + c_score + s_score) / 3

        return f"""
📊 Итоговый отчёт (Generated by AI)
━━━━━━━━━━━━━━━━━━
🎯 {session['direction']} | {session['level']}

📖 Теория: {t_score:.1f}/10
💻 Код: {c_score:.1f}/10
🗣 Soft: {s_score:.1f}/10

🏆 ИТОГ: {total:.1f}/10
"""